cask 'docker-desktop'
cask 'font-maple-mono'
cask 'ghostty'
cask 'rectangle'
cask 'spotify'
cask 'sublime-text'

tap 'qmk/qmk'
brew 'qmk/qmk/qmk'

brew 'asmvik/formulae/skhd'

brew 'bat'
brew 'carapace'
brew 'fzf'
brew 'helix'
brew 'jq'
brew 'lf'
brew 'ripgrep'
brew 'stow'
brew 'terminal-notifier'
brew 'zellij'
brew 'zoxide'

brew 'vacuum'

brew 'postgresql@18'
brew 'sleek'

brew 'ruby'
gem 'rubocop'

brew 'janet'

brew 'node@22'

brew 'dlv'
brew 'go'
brew 'gofumpt'
brew 'goimports'
brew 'gopls'
brew 'gotestsum'
go 'github.com/tomasruud/go-test-skeleton'
go 'github.com/tomasruud/tprompt'
go 'github.com/tomasruud/urlr'

brew 'rustup'
