tap "homebrew/bundle"
tap "openresty/brew"
brew "bat"
brew "ruby"
brew "cocoapods"
brew "php"
brew "composer"
brew "exa"
brew "fd"
brew "flyctl"
brew "fzf"
brew "ghcup"
brew "glab"
brew "go"
brew "grep"
brew "helix"
brew "hurl"
brew "jq"
brew "lua-language-server"
brew "luarocks"
brew "marksman"
brew "mas"
brew "node"
brew "nvm"
brew "opam"
brew "openjdk"
brew "ripgrep"
brew "roswell"
brew "rustup-init"
brew "sevenzip"
brew "stow"
brew "taplo"
brew "tmux"
brew "tree"
brew "openresty/brew/openresty"
cask "alacritty"
cask "docker"
cask "firefox"
cask "gnucash"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "microsoft-teams"
cask "monitorcontrol"
cask "spotify"
cask "sublime-text"
mas "Bitwarden", id: 1352778147
mas "Boxy SVG", id: 611658502
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "Logic Pro", id: 634148309
mas "Messenger", id: 1480068668
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
