tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bat"
brew "cocoapods"
brew "php"
brew "composer"
brew "fd"
brew "glab"
brew "go"
brew "grep"
brew "mas"
brew "neovim"
brew "node"
brew "nvm"
brew "openjdk"
brew "ripgrep"
brew "rustup-init"
brew "sevenzip"
cask "docker"
cask "firefox"
cask "gnucash"
cask "google-chrome"
cask "insomnia"
cask "jetbrains-toolbox"
cask "microsoft-teams"
cask "monitorcontrol"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
cask "warp"
mas "Bitwarden", id: 1352778147
mas "Boxy SVG", id: 611658502
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "Logic Pro", id: 634148309
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Motion", id: 434290957
mas "Plain Text Editor", id: 1572202501
mas "Slack", id: 803453959
mas "Tot", id: 1491071483
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
