#!/bin/bash
set -e

case "$1" in
sync | install)
    stow --verbose --target="$HOME" --restow */
    ;;

uninstall)
    stow --verbose --target="$HOME" --delete */
    ;;

secrets:backup)
    tar -zcvf secrets.backup.tgz $HOME/.ssh $HOME/.netrc $HOME/.env
    ;;

*)
    echo "dotfiles manager

Usage:
    dot <command>

Available commands:
    install - install dotfiles
    uninstall - uninstalls dotfiles
    sync - sync dotfiles
    secrets:backup - creates backup of secrets"
    exit 1
esac
