#!/bin/bash
set -e

case "$1" in
sync | install)
    stow --verbose --target="$HOME" --restow */
    ;;

uninstall)
    stow --verbose --target="$HOME" --delete */
    ;;

secrets:backup)
    tar -zcvf secrets.backup.tgz $HOME/.ssh $HOME/.netrc $HOME/.env
    ;;

brew:backup)
    brew bundle dump --force --file "$HOME/dotfiles/brew/Brewfile"
    ;;

brew:setup)
    brew bundle --file "$HOME/dotfiles/brew/Brewfile"
    ;;

*)
    echo "dotfiles manager

Usage:
    dot <command>

Available commands:
    install - install dotfiles
    uninstall - uninstalls dotfiles
    sync - sync dotfiles
    secrets:backup - creates backup of secrets
    brew:backup - dumps installed brew packages to Brewfile
    brew:setup - installs brew packages from Brewfile"
    exit 1
esac
