#!/usr/bin/env zsh
set -e

function _usage() {
    echo "
Usage:
    nvim-plugin <command>

Available commands:
    install <name> <repo> - install plugin from repo
    uninstall <name> - uninstall plugin"
    exit 1
}

local root="nvim/.config/nvim/pack/plugins/start"

function _install() {
    if [[ "$#" -ne 2 ]]; then
        echo "Error: illegal number of arguments"
        _usage
    fi

    git submodule add -f "$2" "$root/$1"
}

function _uninstall() {
    if [[ "$#" -ne 1 ]]; then
        echo "Error: illegal number of arguments"
        _usage
    fi

    local plugin="$root/$1"
    git submodule deinit -f "$plugin"
    git rm -f "$plugin"
}

case "$1" in
install)
    shift
    _install "$@"
    ;;

uninstall)
    shift
    _uninstall "$@"
    ;;

*)
    echo "nvim plugin manager"
    _usage
esac
