#!/usr/bin/env zsh
set -e

function _usage() {
    echo "
Usage:
    zsh-plugin <command>

Available commands:
    install <name> <repo> - install plugin from specified repo
    uninstall <name> - uninstall plugin"
    exit 1
}

local root="zsh/.config/zsh/plugins"

function _install() {
    if [[ "$#" -ne 2 ]]; then
        echo "Error: illegal number of arguments"
        _usage
    fi

    git submodule add -f "$2" "$root/$1"
}

function _uninstall() {
    if [[ "$#" -ne 1 ]]; then
        echo "Error: illegal number of arguments"
        _usage
    fi

    local plugin="$root/$1"
    git submodule deinit -f "$plugin"
    git rm -f "$plugin"
}

case "$1" in
install)
    shift
    _install "$@"
    ;;

uninstall)
    shift
    _uninstall "$@"
    ;;

*)
    echo "zsh plugin manager"
    _usage
esac
