# Set gofumpt as Go formatter
language-server.gopls.config.gofumpt = true

# Add .tfvar as tfvars ext
[[language]]
name = "tfvars"
file-types = ["tfvars", "tfvar"]

# Ruby should lint and format
[[language]]
name = "ruby"
config = { solargraph = { diagnostics = true, formatting = true } }
