# Set gofumpt as Go formatter
language-server.gopls.config.gofumpt = true
language-server.gopls.config.staticcheck = true
language-server.gopls.config.local = "go.axofinance.io,github.com/tomasruud,gitlab.com/2ms"

# Add .tfvar as tfvars ext
[[language]]
name = "tfvars"
file-types = ["tfvars", "tfvar"]

[[language]]
name = "sql"
formatter = { command = "sleek", args = [] }

# Add openapi lsp
[[language]]
name = "openapi3.json"
grammar = "json"
scope = "source.openapi3.json"
roots = []
auto-format = true
file-types = ["openapi.json"]
language-servers = [
  { name = "vscode-json-language-server", only-features = [
    "format",
  ] },
  "vacuum-lsp",
]
indent = { tab-width = 2, unit = "  " }

[language-server.vacuum-lsp]
command = "vacuum"
args = ["language-server"]

# Ruby
[language-server.rubocop]
command = "rubocop"
args = ["--lsp"]

[[language]]
name = "ruby"
auto-format = true
language-servers = [{ name = "rubocop" }]

# AI
[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = {}

[language-server.lsp-ai.config.models.model1]
type = "ollama"
model = "deepseek-coder"

[[language-server.lsp-ai.config.chat]]
action_display_name = "AI chat ✨"
trigger = "!C"
model = "model1"

[language-server.lsp-ai.config.chat.parameters]
max_context = 4096
max_tokens = 1024

[[language-server.lsp-ai.config.chat.parameters.messages]]
role = "system"
content = "You are a code assistant chatbot. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately"

[language-server.lsp-ai.config.completion]
model = "model1"

[language-server.lsp-ai.config.completion.parameters]
max_context = 2000
options = { num_predict = 128 }
