# Set gofumpt as Go formatter
language-server.gopls.config.gofumpt = true
language-server.gopls.config.local = "go.axofinance.io,github.com/tomasruud,gitlab.com/2ms"

# Add .tfvar as tfvars ext
[[language]]
name = "tfvars"
file-types = ["tfvars", "tfvar"]

[[language]]
name = "sql"
formatter = { command = "sleek", args = [] }

# Add openapi lsp
[[language]]
name = "openapi3.json"
grammar = "json"
scope = "source.openapi3.json"
roots = []
auto-format = true
file-types = ["openapi.json"]
language-servers = [
  { name = "vscode-json-language-server", only-features = [
    "format",
  ] },
  "vacuum-lsp",
]
indent = { tab-width = 2, unit = "  " }

[language-server.vacuum-lsp]
command = "vacuum"
args = ["language-server"]

# Ruby
[language-server.rubocop]
command = "rubocop"
args = ["--lsp"]

[[language]]
name = "ruby"
auto-format = true
language-servers = [{ name = "rubocop" }]
