# Set gofumpt as Go formatter
language-server.gopls.config.gofumpt = true

# Ruby should lint and format
language-server.solargraph.config.formatting = true
language-server.solargraph.config.diagnostics = true

# Add .tfvar as tfvars ext
[[language]]
name = "tfvars"
file-types = ["tfvars", "tfvar"]

# Add openapi lsp
[[language]]
name = "openapi3.json"
grammar = "json"
scope = "source.openapi3.json"
roots = []
auto-format = true
file-types = ["openapi.json"]
language-servers = ["vacuum-lsp"]

[language-server.vacuum-lsp]
command = "vacuum"
args = ["language-server"]
