syntax on
set background=light
colorscheme solarized

" tabs
autocmd Filetype go setlocal tabstop=2  softtabstop=4 expandtab

set number
set showcmd
set cursorline

filetype indent on

" set wildmenu

set lazyredraw

set showmatch

set incsearch
set hlsearch

" go stuff
filetype plugin indent on
let g:go_fmt_command = "goimports"     
let g:go_auto_type_info = 1 

" NERDTree plugin specific commands
:nnoremap <C-g> :NERDTreeToggle<CR>

