format = """
$directory\
$git_branch\
$git_state\
$git_status\
\\$ """

right_format = "[$username@$hostname](dimmed)"
add_newline = false
scan_timeout = 10
command_timeout = 100

[git_branch]
format = '\[[$branch(:remote_branch)](bold purple)'

[git_status]
format = '$ahead_behind(|$staged$conflicted$stashed$deleted$renamed$modified$untracked)\]'
ahead = '↑${count}'
behind = '↓${count}'
diverged = '↑${ahead_count}↓${behind_count}'
untracked = '…$count'
stashed = '[⚑$count](blue)'
modified = '[✚$count](red)'
staged = '[●$count](green)'
renamed = '[✚$count](red)'
deleted = '[✖$count](red)'

[directory]
format = '$path'

[hostname]
format = '$hostname'
ssh_only = false

[username]
format = '$user'
show_always = true
