format = '$directory\$ '
right_format = "[$username@$hostname](dimmed)"
add_newline = false
scan_timeout = 10
command_timeout = 100

[directory]
format = '$path'

[hostname]
format = '$hostname'
ssh_only = false

[username]
format = '$user'
show_always = true
