#!/bin/bash
npm i -g \
  dockerfile-language-server-nodejs \
  intelephense \
  typescript-language-server \
  typescript \
  vscode-langservers-extracted \
  bash-language-server

go install mvdan.cc/gofumpt@latest
go install golang.org/x/tools/gopls@latest
