#!/bin/bash

if command -v "go" > /dev/null 2>&1; then
  go install mvdan.cc/gofumpt@latest
  go install golang.org/x/tools/gopls@latest
  go install github.com/go-delve/delve/cmd/dlv@latest
  go install github.com/daveshanley/vacuum@latest
else
  echo "go is not installed, skipping some elements"
fi

if command -v "npm" > /dev/null 2>&1; then
  npm i -g \
    dockerfile-language-server-nodejs \
    intelephense \
    typescript-language-server \
    typescript \
    vscode-langservers-extracted \
    bash-language-server
else
  echo "node/npm is not installed, skpping some elements"
fi

if command -v "gem" > /dev/null 2>&1; then
  gem install solargraph
else
  echo "ruby/gem is not installed, skpping some elements"
fi
