#!/bin/bash

if ! command -v "go" > /dev/null 2>&1; then
  echo "You must install go to continue..."
  exit 1
fi

if ! command -v "npm" > /dev/null 2>&1; then
  echo "You must install npm/node to continue..."
  exit 1
fi

npm i -g \
  dockerfile-language-server-nodejs \
  intelephense \
  typescript-language-server \
  typescript \
  vscode-langservers-extracted \
  bash-language-server

go install mvdan.cc/gofumpt@latest
go install golang.org/x/tools/gopls@latest
go install github.com/go-delve/delve/cmd/dlv@latest
