#!/bin/sh

tar -zcvf $HOME/dotfiles/$(hostname)-$(date +%Y-%m-%d)-secrets.backup.tgz \
	$HOME/.ssh \
	$HOME/.netrc \
	$HOME/.env* \
	$HOME/.gitconfig.local \
	$HOME/AGENTS.md \
	$HOME/.claude-private \
	$HOME/.zsh_history \
	$HOME/.usql_history \
	$HOME/notes.md \
	$HOME/.aws/config
