#!/bin/bash

files=(
    "$HOME"/.env*
    "$HOME"/.psql_history*
    "$HOME/.aws/config"
    "$HOME/.gitconfig.*"
    "$HOME/.netrc"
    "$HOME/.pg_service.conf"
    "$HOME/.pgpass"
    "$HOME/.ssh/config"
    "$HOME/.ssh/known_hosts"
    "$HOME/.usql_history"
    "$HOME/.zsh_history"
    "$HOME/notes.md"
)

existing=()
for f in "${files[@]}"; do
    [ -e "$f" ] && existing+=("$f")
done

tar -zcvf "$HOME/secrets-$(hostname)-$(date +%Y-%m-%d).backup.tgz" "${existing[@]}"
