#!/bin/sh

brew bundle --global

jpm install jpm
jpm install spork
jpm install judge
jpm install https://github.com/CFiggers/janet-lsp.git

npm i -g dockerfile-language-server-nodejs
npm i -g intelephense
npm i -g typescript-language-server
npm i -g typescript
npm i -g vscode-langservers-extracted
npm i -g bash-language-server
npm i -g prettier
npm i -g @mariozechner/pi-coding-agent
