#!/bin/bash

sudo apt update
sudo apt upgrade

# Install some dependencies
sudo apt install git zsh stow curl build-essential gcc make fzf tmux

# Set zsh as default shell
sudo chsh -s $(which zsh) $(whoami)

# Install Rust
if [[ -e "$HOME/.cargo/env" ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    source $HOME/.cargo/env
fi

cargo install eza
cargo install fd-find

