#!/bin/bash

# install some dependencies
sudo apt update
sudo apt upgrade
sudo apt install git zsh stow curl build-essential gcc make fzf tmux php php-common php-curl mosh elvish ruby-full

# set zsh as default shell
sudo chsh -s $(which elvish) $(whoami)

# install Rust
if ! command -v "cargo" > /dev/null 2>&1; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    source $HOME/.cargo/env
fi

# install Node+npm
if ! command -v "npm" > /dev/null 2>&1; then
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&\
    sudo apt install -y nodejs
fi
