#!/bin/bash

# install some dependencies
sudo apt update
sudo apt upgrade
sudo apt install git zsh stow curl build-essential gcc make fzf tmux php php-common php-curl mosh

# set zsh as default shell
sudo chsh -s $(which zsh) $(whoami)

# install Rust
if [[ -e "$HOME/.cargo/env" ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    source $HOME/.cargo/env
fi

# install Rust based tools
cargo install eza
cargo install fd-find

# sync dotfiles
$HOME/dotfiles/dot/sync

# install LSPs
$HOME/dotfiles/helix/setup-lsps

# install binaries
$HOME/dotfiles/bin/install
