#!/bin/bash

# install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# add Homebrew binaries to path
export PATH="$PATH:/opt/homebrew/bin"

# clone the repo
git clone https://github.com/tomasruud/dotfiles.git $HOME/dotfiles

# install Homebrew packages
brew bundle --file "$HOME/dotfiles/brew/Brewfile"

# set default rust toolchain
rustup default stable

# set elvish as default shell
elvish "$HOME/dotfiles/osx/default-shell.elv"

cd $HOME/dotfiles

make install
make tools
